### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by FabianTerhorst**
* AGP 2.3.2 -> 3.0.0-beta2
* Kotlin 1.1.2-4 -> 1.1.4
* Support 25.3.1 -> 26.0.1
* Gradle 3.3 -> 4.1

### CODE REVIEW

**Comment by Arasthel** [comment]
Thanks for the PR, but I'd rather wait until the Android Gradle Plugin comes out of beta to update it.

**Comment by FabianTerhorst** [comment]
Many popular libraries, including https://github.com/NYTimes/Store, already migrated to the 3.0 plugin. I don´t see any disadvantages there.

**Comment by jaumard** [comment]
Android studio 3.0 is in stable version now :)

**Comment by Arasthel** [comment]
Closing this as dependencies are already updated. Thanks for the PR 👍 .

**Pull request closed without merging**
